### ISSUE TITLE
Screenshots from the carrousel should change automatically

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#101]
Yeah...pretty much that. I guess like 5 seconds per scroll seems fine.

**Comment by DerErizzle** [comment]
I like this feature, just wanted to add that the scroll should probably stop when you hover over the screenshot with your mouse

**Comment by AkiraArtuhaxis** [comment]
> I like this feature, just wanted to add that the scroll should probably stop when you hover over the screenshot with your mouse

Agreed.
Better yet, I think if you click on the carrousel the screenshots should get bigger (like what happens on the Steam store).
