### ISSUE TITLE
Patch versions not getting checked when opening the Patcher fast enough

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#108]
If you open the Patcher fast enough right as the loading screen ends, some games don't get their versions checked.
![NotCheckedGames](https://github.com/AlexisL61/JackboxUtility/assets/93792993/1d5fa808-099e-4cd7-8f13-c2e1b942b774)

**Comment by AlexisL61** [comment]
This is a problem with the automatic version finder from the repo. applyExternalConfiguration() should be awaited here.
https://github.com/AlexisL61/JackboxUtility/blob/dev/jackbox_patcher/lib/services/api/api_service.dart#L85
