### ISSUE TITLE
Add a notification on the title screen when there is something that can be patched / updated

### ISSUE THREAD

**Issue by DerErizzle** [AlexisL61/JackboxUtility#126]
![image](https://github.com/AlexisL61/JackboxUtility/assets/43215958/16c852b2-fbba-4e12-903a-902630b40438)

**Comment by AkiraArtuhaxis** [comment]
Text is not needed for this. Only a small red dot should be able to signify this. It should disappear when there aren't updates available.
![Notification Mockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/5dd310f0-3969-49a9-a71d-2871c7298cdf)
Small problem: On the Spanish team, we have two different categories. So, in order for the dot to not appear, if everything from **one** category is updated, the dot shouldn't appear.
