### ISSUE TITLE
Add an option to filter by number of players

### ISSUE THREAD

**Issue by GsakuL** [AlexisL61/JackboxUtility#143]
Why:
- e.g. Trivia Murder Party could even be played solo (1-8)
  - but realistically, I would like to filter hide "3-*" etc.
- some games are 6 people max (active players, not counting audience) - would obviously not work in a group/call of 7+ people
- mouse-over shows players, but if you show the nice list to the group, people will ask again and again

How:
maybe a text/number-box, where you can enter the current amount of players? (obviously off/null by default)
A vertical/horizontal list of buttons would be rather long/wide (eg Bracketeering is 16 max); and a Slider/Range may be "too sensitive"; but these would naturally limit the options.

Or something built into the search bar? maybe if "all text is just a single number"? Or a prefix/tag thingy (like GitHubs Issue search field), though that may be too obscure/counter-intuitive

**Comment by AkiraArtuhaxis** [comment]
This is already issued in the [Launcher settings](https://github.com/AlexisL61/JackboxUtility/issues/91#issue-1708789324) issue.

**Comment by AlexisL61** [comment]
Yes, this will add with the #91 issue. I am closing this issue as a duplicate
