### ISSUE TITLE
Server info redesign

### ISSUE THREAD

**Issue by MeDustyy** [AlexisL61/JackboxUtility#161]
I've already shared these ideas on Discord, but it might be better to create an issue here.
- 1:
![](https://cdn.discordapp.com/attachments/1108095925928329218/1109139421393072128/image_2023-05-19_17-20-253.png)
- 2:
![](https://cdn.discordapp.com/attachments/1108095925928329218/1109139421724418048/image_2023-05-19_17-20-252.png)
- 3:
![](https://cdn.discordapp.com/attachments/1108095925928329218/1109139422076747857/image_2023-05-19_17-20-251.png)

**Comment by AkiraArtuhaxis** [comment]
Personally, I like the first one better.

**Comment by AlexisL61** [comment]
Following the first one, the current build looks like this : 
![image](https://github.com/AlexisL61/JackboxUtility/assets/30233189/7eafba3f-ef4a-476b-ae67-259c128c0895)
