### ISSUE TITLE
Arrow direction

### ISSUE THREAD

**Issue by MeDustyy** [AlexisL61/JackboxUtility#165]
The arrow next to the filter button should point up when the filter menu is closed and down when the filter menu is open.
![Знімок екрана 2023-06-23 102751](https://github.com/AlexisL61/JackboxUtility/assets/58863601/962e490d-1acd-4b0c-96a6-c85ec3b0f44e)

**Comment by AlexisL61** [comment]
The current arrow direction is the normal behavior for most applications

**Comment by MeDustyy** [comment]
Yes, I'm a bit confused. The arrow is correct.

But it would probably be better if the filter menu expanded upwards (the Filter button should not move). All other menus on this page do not move themselves when expanded. That's why I thought there was something wrong with the arrow.
![image](https://github.com/AlexisL61/JackboxUtility/assets/58863601/9d56f731-f97c-42f9-b1bc-e3c9894a86ec)

**Comment by AkiraArtuhaxis** [comment]
I see nothing wrong with the arrow. That's how it appears in most apps.
