### ISSUE TITLE
Titles of disabled filters

### ISSUE THREAD

**Issue by MeDustyy** [AlexisL61/JackboxUtility#166]
Titles of disabled filters are very hard to see. I suggest using the same text color for both enabled and disabled filters.
![Знімок екрана 2023-06-23 103340](https://github.com/AlexisL61/JackboxUtility/assets/58863601/a8240df8-29bb-4e3d-9437-562d25c02f48)

**Comment by AlexisL61** [comment]
I agree that it is hard to see, maybe we should use a lighter grey?
