### ISSUE TITLE
Arrow from "Add a game" dropdown menu is misplaced and doesn't change from down to up

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#172]
![AddAGameArrow](https://github.com/AlexisL61/JackboxUtility/assets/93792993/ee72cfc7-0cf4-4446-bcbd-ccbd236b5e14)
![AddAGameArrow2](https://github.com/AlexisL61/JackboxUtility/assets/93792993/c0b44ec9-2c8c-4434-b8b7-1980c6fdc0a1)

**Comment by AlexisL61** [comment]
It's alright on my end, strange
![image](https://github.com/AlexisL61/JackboxUtility/assets/30233189/2050b9aa-996a-4fee-bb3d-93fecf7159c1)

**Comment by AkiraArtuhaxis** [comment]
That's weird. It does look messed up in my end.

**Comment by AkiraArtuhaxis** [comment]
I figured out why this happens.
The YDKJ game titles are too long and thus make the arrow look misplaced.
I think the only problematic one is "You Don't Know Jack Vol. 6 The Lost Gold" (that's the title it has on Steam so I'd prefer to not change it). Maybe making the window a little bit longer would solve the issue?
![imagen](https://github.com/AlexisL61/JackboxUtility/assets/93792993/88a48ef8-128a-4674-8243-a414f475faab)

**Comment by AkiraArtuhaxis** [comment]
If the window can't be made longer, I'll just remove "The Ride" and "The Lost Gold" from the titles.
