### ISSUE TITLE
Change top texts when selecting a server

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#186]
The server selection screen will not appear when the user first opens the app. So, the "Welcome to Jackbox Utility" and "Select a language to begin" texts don't really make sense.
I suggest changing it to "Select one of the available servers" or something similar.
![ServerSelectionScreen](https://github.com/AlexisL61/JackboxUtility/assets/93792993/fbc2dc25-9a15-456b-91b8-34103667f58b)

**Comment by AlexisL61** [comment]
Need translation for the `select_server_subtitle` string for : 

- [ ] Spanish
- [ ] Deutsch
- [ ] Ukrainian

**Comment by AkiraArtuhaxis** [comment]
Spanish: Selecciona uno de los servidores disponibles

**Comment by Forseti6676** [comment]
I would say for German: Wähle einen der verfügbaren Server

**Comment by AlexisL61** [comment]
@allcontributors please add @Forseti6676 for translation
