### ISSUE TITLE
SFX tweaks

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#206]
The same SFX that plays when you click a star should play:
  - [x] When you press the "Hide game" button.
  - [x] When you press a filter toggle.
  - [x] When you press the arrow to change sorting.
  - [x] When you press the "Show games you've hidden" button.
  - [x] When you press the "Show unowned games" button.
- [x] The same SFX that plays when you hover over a star should play when you hover over a Filter button.
- [x] The SFX when you go enter a game info tab should play when you press one of the clickable buttons from each game info tab (Translated by the community, tags, etc).
- [x] The SFX when you go back from the game info tab should play when you go back from the Launcher to the title screen for consistency.
- [x] The SFX when you go back from the game info tab should play when you go back after pressing the clickable buttons from each game info tab (Translated by the community, tags, etc).
- [x] If possible, I'd also make it so the play button SFX begins playing as soon as you click the button and not when the game starts launching.
- [x] On the "Random" tab, every time a banner gets shuffled in the "Let's try another one!" animation the hover over banner SFX should play.
- [x] When opening and closing the Filter menu, I suggest these SFX: [sfx.zip](https://github.com/AlexisL61/JackboxUtility/files/11931171/sfx.zip)

**Comment by AkiraArtuhaxis** [comment]
- When you leave the "Random game" tab, the hover SFX plays. This shouldn't be the case.
- Sometimes, when filters are applied, the random shuffle SFX gets either cut or replaced by one of the SFX from the Filter. This shoulnd't be the case and only the shuffle SFX should play.
- Make "click" SFX (when clicking on Stars, hidden game button, etc) not able to be cut by other SFX.
- Make hover and "click" SFX when you hover/click the button to remove all filters.
- Make "leave" SFX (when you go back from a game info tab) not able to be cut by other SFX.
- "Leave" SFX doesn't play when you press ESC on the buttons from the game info tabs (Translated by the community, Coop, etc). It does play when you click the back button. It should play in both cases.
- When you click a Star, that same Star you're hovering on shouldn't play a SFX when you move the mouse. Only when you hover over one of the ones next to it it should play.
- When you open the "Sort by" menu, the SFX when you open the filter should play.
- When you don't select a sorting (press outside the button), the SFX when you close the filter should play.
- When clicking the tabs on the sidebar (and the games appear), I suggest this SFX: [sfx.zip](https://github.com/AlexisL61/JackboxUtility/files/11941729/sfx.zip)

**Comment by AlexisL61** [comment]
The checkbox that are not checked cannot be done right now
