### ISSUE TITLE
Explanations when hovering over game information

### ISSUE THREAD

**Issue by MeDustyy** [AlexisL61/JackboxUtility#212]
I think it will be easier to understand the meaning of the information about the game
![Знімок екрана 2023-07-03 2127191](https://github.com/AlexisL61/JackboxUtility/assets/58863601/aa6be001-9202-42c0-9809-22d4b38972a6)

**Comment by MeDustyy** [comment]
Maybe I wrote the explanation on the screenshot wrong.
Here's why it's important😉

**Comment by AkiraArtuhaxis** [comment]
I mean, this only really works with the Stream Friendly setting. The other 4 are pretty self explanatory imo. And for that setting you already have the descriptions if they're needed (you can just add that text in the screenshot to the description and it'll appear in the square).

**Comment by MeDustyy** [comment]
> I mean, this only really works with the Stream Friendly setting. The other 4 are pretty self explanatory imo. And for that setting you already have the descriptions if they're needed (you can just add that text in the screenshot to the description and it'll appear in the square).

For those who are not very familiar with Jackbox Games, Audience and Moderation may also be incomprehensible.

**Comment by AkiraArtuhaxis** [comment]
I suppose that's true. Well, maybe this can work then (even though I doubt this app will be used by people that barely know about the Jackbox games).
