### ISSUE TITLE
Show version numbers in "All patches"

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#23]
Both version numbers (the one that the user currently haves and the one that's currently available) should appear in the top right corner of each game tab in the "All patches" section. They should have different colors to indicate which is which.
![VersionNumber](https://user-images.githubusercontent.com/93792993/232235298-a5f1b6a0-e9b7-438a-9090-89e1888eb58a.png)

**Comment by AlexisL61** [comment]
Added, should be available in the next Internationalization build
