### ISSUE TITLE
Translate remaining strings

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#24]
These strings should be translated:

- All patches
- Show all packs
- "Install patch" should be "Install patches" in the "All patches" section. Same with "Patches installed".
- Version
- Download in progress
- A download is in progress, are you sure you want to quit now ?

**Comment by AkiraArtuhaxis** [comment]
Also "quit", which I forgot.

**Comment by DerErizzle** [comment]
![image](https://user-images.githubusercontent.com/43215958/232248228-9541b5cf-9ada-4473-9c77-44ff8abcc346.png)
