### ISSUE TITLE
Bug: Pressing ESC while a download is in progress

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#25]
Pressing ESC while a download is in progress will cause the download screen to not be visible, but the download will still keep going. After this, you can press the "Install patch" button again for the download to start again. The progress bar at the bottom will also go really crazy after doing this.

Either there should be a proper "Cancel" button which functions like one or the user shouldn't be able to close this window by pressing ESC.

**Comment by AlexisL61** [comment]
It is currently not possible to prevent the patch installation cancelation using the ESC button. This issue will stay with the "blocked" label until the issue https://github.com/bdlukaa/fluent_ui/issues/826 is closed.
