### ISSUE TITLE
Discord rich presence doesn't show which game I'm playing

### ISSUE THREAD

**Issue by KosMos-pv** [AlexisL61/JackboxUtility#262]
When I start my game it doesn't update and show only "choosing a game" or "reading information of a game". It should detect running game and show launched game. Now I have to stay on game page to show which game I started.

**Comment by AlexisL61** [comment]
First, thank you for your issue !
Long story short, fort the moment we can detect when a game is launched by the utility (so we know which game you are playing) but we can't know when you switch between games in the party pack.
We are still on-work to see if we can detect it by modifying the game file, but for the moment it is not available

**Comment by KosMos-pv** [comment]
I understand this. So for mow when you can only detect pack but not game in this pack make this optional. So I can enable this feature manually and will be warned about possibility to detect only first launched game in pack.

Maybe add button to game page to manually set status if pack containing this game is launched. This is not ideal and not all players will manually switch status but letting switch manually - why not if someone ready to do this?

**Comment by AlexisL61** [comment]
The app now supports Rich Presence for packs (next update). I will open a new issue to supports Rich Presence for games
