### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [AlexisL61/JackboxUtility#295]
GPLv2 https://hosted.weblate.org/projects/jackboxutility/jackboxutility_app/#information
isn't compatible with
GPLv3 https://github.com/AlexisL61/JackboxUtility/blob/dev/LICENSE

I would advice going "or-later" instead of restricting to "only" to avoid further incompatibilities.

It can be changed in
https://hosted.weblate.org/settings/jackboxutility/jackboxutility_app/
and
https://hosted.weblate.org/settings/jackboxutility/glossary/

**Comment by AlexisL61** [comment]
It has been changed, thank you very much for the issue !

**Comment by comradekingu** [comment]
@AlexisL61 
It got changed to GPLv**2**-or-later, but I think it should be GPLv**3**-or-later.

**Comment by AlexisL61** [comment]
Should be fixed
