### ISSUE TITLE
Bug: Incorrect information on game paths

### ISSUE THREAD

**Issue by DerErizzle** [AlexisL61/JackboxUtility#30]
![image](https://user-images.githubusercontent.com/43215958/232250448-44fb721b-fc67-4af6-940c-58a43750c122.png)
In this screenshot, I manually set PP2 to an incorrect path.

Now, when I click on the "remove" button on the right to delete PP2, it says "path not found" on PP3. When PP3 is deleted, it moves to PP4, and so on
![image](https://user-images.githubusercontent.com/43215958/232250697-a9fce27a-3e90-4076-8028-a213e59e332a.png)

**Comment by AlexisL61** [comment]
[video](https://cdn.discordapp.com/attachments/1085647431598870559/1099701665336143872/2023-04-23_16-20-32.mp4)
