### ISSUE TITLE
Launch games through the Utility via command line

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#313]
Definitely low priority. If it's not hard to do, it'd be useful to users that use Launchbox or similar launchers to add individual games there.

**Comment by AlexisL61** [comment]
Documentation (to be redacted in a better way and in the Readme.md) : 

- Launch game : ./JackboxUtility.exe launch game <gameId>
- Launch pack : ./JackboxUtility.exe launch pack <packId>

The gameId and packId are ids used by the server the user is connected to.
