### ISSUE TITLE
Support dynamic url to patch via api.github

### ISSUE THREAD

**Issue by easysugar** [AlexisL61/JackboxUtility#321]
Instead of rewriting the patch_url every time, it's better to use api.github for retreival the url to patch in the latest release. 
For example, a link `https://api.github.com/repos/easysugar/jackbox-starter-pack-ua/releases/latest` returns an attribute `browser_download_url` which already contains the url to the patch archive in the latest release. So, you don't need to update the patch_url in the Jackbox Utility server.

**Comment by AkiraArtuhaxis** [comment]
You can already not update the patch links every time. Just use a link like this: https://github.com/AkiraArtuhaxis/The-Jackbox-Party-Pack-1-Spanish/releases/latest/download/JPP1-ES.zip
We never need to update the patch url.

**Comment by easysugar** [comment]
It's not a solution for me, because I use different names of the patch files for different release version.

**Comment by AkiraArtuhaxis** [comment]
Uhh, I suppose that's fair, although I don't see why you'd need different names of the files anyways. The Utility doesn't show those.

**Comment by easysugar** [comment]
@AkiraArtuhaxis 
Agree. I will switch to the equal names of the patches. However, should I also update an attribute `"version": "216.14-UK"` in the patchs section?

**Comment by AlexisL61** [comment]
If you are using the "configuration" attribute in your patch, the version will be based on this attribute (so you don't need to add a version attribute in your patch, it will be retrieved automatically by the app)

**Comment by easysugar** [comment]
Oh, thank you. It'll help!
