### ISSUE TITLE
Someone claims to be creating a project similar to this.

### ISSUE THREAD

**Issue by ghost** [AlexisL61/JackboxUtility#326]
Hi, I just wanted to let you know that Twitch user shes_a_rebel on her Twitter account is claiming to be creating a project similar to yours, and I wanted everyone to see the screenshots to see if she was serious about making this on her own, or if she was piggybacking off of someone elses work.

[Here](https://twitter.com/goawaypudding/status/1703693961930641833?t=yQmmR5gTxPAnJ6orlmmbEQ&s=19)

**Comment by AlexisL61** [comment]
Hello there, the screenshots don't look like JackboxUtility at all.

**Comment by SluttyStinker** [comment]
Thank you so much for letting me know, just wanted to be sure
