### ISSUE TITLE
Remove right click behavior on game banner

### ISSUE THREAD

**Issue by Nutzzz** [AlexisL61/JackboxUtility#332]
Left-click to open the game info screen and right-click to open the game immediately is strange UX.  I appreciate that there's (currently) no context menu, but as a new user I was expecting there might be one.  I do like that there's a way to open the games immediately, but this would normally be achieved with a double-click (even though waiting to see if the second click occurs obviously complicates the logic).  If doing double-click is too much trouble, middle-click is a possibility.

In any case, the smaller play button does exist, which might not be immediately obvious, but I feel it's sufficient so that you might just remove right-click and not change any other behavior.

**Comment by AkiraArtuhaxis** [comment]
I agree with this. Right click feels pointless now that there's a play button (before, there wasn't one). Sometimes I misclick the right click and it launches the game, which I'd prefer not to happen. Middle click to do this isn't really necessary, as the play button exists now.
