### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by DerErizzle** [AlexisL61/JackboxUtility#34]
A UI-Designer from our team carefully looked at the Utility and raised a few minor suggestions to enhance the user experience.

- When the mouse hovers over a button or clickable object, it should transform into a pointer. This way, the user knows that they can click the object. This is already a thing in the main menu where the user can decide between launching and patching a game, but it should apply everywhere

- When an info screen is opened (notifications, patch info, path settings), clicking next to it (into the void) does nothing but play the Windows error sound. Instead, it should close the info screen

- In the patch-section, the "Info" icon for the game and the patch info is identical, but lead to a different destination. Maybe we can change the patch info icon to a hamburger to avoid confusion. Also the blue info hover effect is not perfectly aligned if you look closely.
![image](https://user-images.githubusercontent.com/43215958/232302545-f20d309f-c4c1-4d81-8357-d80e2186696a.png)

**Comment by AkiraArtuhaxis** [comment]
Disagree with the fix of the last point.
Instead, I think just putting in plain text "Description" (while hovering) without an icon would be enough to differentiate the two screens.
