### ISSUE TITLE
Autodetecting games duplicates game list

### ISSUE THREAD

**Issue by DerErizzle** [AlexisL61/JackboxUtility#44]
![image](https://user-images.githubusercontent.com/43215958/234295295-21ebcda4-093e-40ce-9d3a-1ea37c30799b.png)
No idea why this happens, but if you manually click on "Auto-detect installed games", every game game gets duplicated. This also applies to the launcher: When you click on "Auto-detect installed games" five times, you'll find every game five times in the launcher. It also "finds" all of the already found games.
![image](https://user-images.githubusercontent.com/43215958/234295969-bc4eaf7b-d0f2-4a56-8d4c-3465937eeec7.png)
![image](https://user-images.githubusercontent.com/43215958/234296069-d994608e-a1a8-4358-b0f2-2501289d5e07.png)

**Comment by AkiraArtuhaxis** [comment]
Issue not yet fixed. Games still duplicate when you enter the Settings and go back to the main screen.

**Comment by AlexisL61** [comment]
Fix in release.
