### ISSUE TITLE
Title screen background

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#59]
Since the background in the title screen is just plain grey, it was suggested to have a collage-styled background, similar to the concept in the image.
It can use characters not only from Quiplash, but also from other Jackbox games.
![TitleScreen](https://user-images.githubusercontent.com/93792993/235364022-d0d951b9-8397-48a2-a040-5eb1f288093e.png)

**Comment by AlexisL61** [comment]
Before adding anything, we need the background. I added the "help wanted" label.
