### ISSUE TITLE
Search by Pack: Play Button

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#63]
Since the Standalone games have one game each, would be nice if in the "Search by Pack" tab, there was an option for "Standalone" games in which all of those can be in one nice tab.
Ideally, those games that aren't made by Jackbox Games would be in their own tab as well.
![SearchByPackMockup](https://user-images.githubusercontent.com/93792993/235364621-c3b82ee2-5ddb-4bd1-b637-71f57ffeb87b.png)

**Comment by DerErizzle** [comment]
I would like to add that I am not a fan of this change. The current arrangement of the games is perfect imo

**Comment by AkiraArtuhaxis** [comment]
Repurposed this issue in order to also add another function.
Instead of this change, like Erizzle suggested, I'd add separators between the Packs, Standalones, Classic YDKJ and Non-Jackbox, more as a detail than anything.
![Separators](https://github.com/AlexisL61/JackboxUtility/assets/93792993/eaedd184-82d8-4d62-a92e-f96f6adcbd11)
Finally, I'd remove the dropdown menu from each Info game tab and instead add a Play button in each Pack tab in order to boot to the Party Pack menu with the intro.
![PlayButtonMockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/55c0f3b1-0104-4c98-9443-a1066438555b)
![NoDropdownMenu](https://github.com/AlexisL61/JackboxUtility/assets/93792993/0574d693-6201-4575-8241-dfa47d5909be)

**Comment by AkiraArtuhaxis** [comment]
Repurposed this issue (again) since separators are just unnecessary. Most people don't have all of the games installed (since most of them are obsolete), so separators would only look awkward. Standalone games already stand up by themselves. Plus, at most, people have Drawful 2 installed as their only standalone game.
However, the change of moving the Play button to the "Search by Pack" tab will remain.
