### ISSUE TITLE
Wrong path is considered as a correct path

### ISSUE THREAD

**Issue by DerErizzle** [AlexisL61/JackboxUtility#83]
When changing the folder using the settings wheel in the "Patch a game" section, you can change it to a different game folder (in this example, change PP9 folder to PP2) and the app accepts it as a valid input.
![image](https://github.com/AlexisL61/JackboxUtility/assets/43215958/4f82064d-0375-4ca1-b828-adf871d41ee8)

We could either replace the settings wheel with the folder button from the settings menu, with the same effect OR check if the correct .exe file is located at the folder the user selected. Or both, which would be perfect imo

**Comment by AlexisL61** [comment]
@DerErizzle 
What if we delete the path changed display here and we redirect the user to the settings when he clicked on the button ? (That could also fix the #82)
