### ISSUE TITLE
Launcher Settings

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#91]
Below the "Search by tags" tab, there should be a "Settings" tab in which you can enable or disable the things you need in your game session. If a game doesn't have the feature you enable, it should hide. For example, if you enable Family-Friendly, then games like YDKJ and TMP should not appear. These settings should be:

- **Number of players**: Just a simple counter that goes up or down. 4 should be the default one, as that's the count every single game allows. Probably "16+" should be the max one, since going from 17-100 seems kinda useless as only Lie Swatter allows that amount of players.
- **Max Playtime**; Just like the number of players, a simple counter, but this one goes up or down by five. 30 should be the default one, as that's the highest playtime from the game that has it (Roomerang).
- **Family-Friendly**: Two types of dots. Green (is Family-Friendly) or Red (isn't Family-Friendly). Each info tab would explain if it's optional or not.
- **Audience**: Green (yes) or Red (no). Each info tab would explain its role in the game.
- **Stream-Firendly**: This one would have three levels: Green (completely playable on streams), Orange (kinda playable/not playable by Twitch chat; mostly recommended through a Discord call or something) and Red (completely unplayable on stream). Just like the Audience, each info tab would explain the exact reasoning it has that Status.
- **Moderation**: Similar to the Stream-Friendly setting. Green (has moderation/doesn't need it), Orange (has Manual Censoring and/or Bad word filter only) and Red (no moderation).
- **Subtitles**: Green (yes) or Red (no).
![SettingsMockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/6538983f-4d88-41c8-9862-fb9780789902)
![InfoMockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/2b76441e-d33a-44a9-845c-9baeb2bbf111)

There are two more settings stated in jackboxgames.com, but I thought they were useless (since pretty much all the games have this). Mentioning them anyways just in case:

- Extended Timers
- Start From Controller Only

**Comment by DerErizzle** [comment]
I'd limit the number of players to 10 (or maybe 11), since only two games have 11+ players. I'd also suggest to remove the maximum playtime, since those can vary greatly and I don't believe that it's an accurate filter for games. Also, I'd replace the YouTube with the Twitch logo for "Stream-Friendly"

**Comment by DerErizzle** [comment]
Also, what is "Moderation"? The mods-approve-something-beforehand thing? Or does it include the VIP being able to manually censor something? I don't know if we should include this because Jackbox had basic moderation settings early on. They just improved it and added more options from time to time

**Comment by AkiraArtuhaxis** [comment]
> I'd limit the number of players to 10 (or maybe 11), since only two games have 11+ players. I'd also suggest to remove the maximum playtime, since those can vary greatly and I don't believe that it's an accurate filter for games. Also, I'd replace the YouTube with the Twitch logo for "Stream-Friendly"

Agreed with this. "11+" should be the max option.
About the max playtime, this is just to basically hide the games that last the longest (Roomerang, Push The Button, etc). If it doesn't end up being too intuitive we can consider removing it.
The icon of Stream-Friendly is represented by YouTube because this is also meant for people that stream the games through Discord/Zoom/Meet/whatever. The YouTube icon, being basically the icon of a video, represents this a bit better than Twitch. But Twitch could also work. Maybe we can find another icon which could fit for both things.

> Also, what is "Moderation"? The mods-approve-something-beforehand thing? Or does it include the VIP being able to manually censor something? I don't know if we should include this because Jackbox had basic moderation settings early on. They just improved it and added more options from time to time

That's the reason Moderation has three levels. The games that have green-level moderation are the ones that have the mods-approve-something-beforehand thing, while the orange games only have the VIP manually censoring stuff. This is to signify complete moderation (or no moderation needed) and limited moderation, while still fully explaining in detail each moderation feature on each info tab.

**Comment by AkiraArtuhaxis** [comment]
Small update regarding this: Probably the icon for "screencast" is the one we're looking for the "Stream-Friendly" tab. Represents streaming perfectly and works for both Twitch and Discord.
![Screencast](https://github.com/AlexisL61/JackboxUtility/assets/93792993/4dc5680b-6ead-45cc-829f-56d87ee8b0df)

**Comment by AlexisL61** [comment]
As the other fixes to add are in other issues, we can close #91
