### ISSUE TITLE
Optional videos in place of the screenshot carrousel

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#92]
Instead of the screenshot carrousel, videos with sound (like the Party Pack preview videos) should be able to play if they're included in packs.json.

**Comment by DerErizzle** [comment]
Like I said before, this is something we definitely don't want to use, for a variety of reasons (including unwanted sound, and file size: When do the videos should get downloaded? Before opening the launcher? Assuming only 20 MB for every video, that'd require more than 1 GB for all of the games together). But again, if this is optional, feel free to do it on your server lol

**Comment by AkiraArtuhaxis** [comment]
- [ ] Make the videos pause when you hit Play in a game info tab.
- [ ] Making the video full-screen on a second screen (on a dual monitor setup) will make the Utility disappear from the screen. You can only make it appear again by pressing ESC, minimizing and maximizing the screen.
- [ ] If you scroll to a game info tab that has video, the Utility freezes and you can't even close it.
- [ ] If you're in full-screen and let the video finish playing, you can't play the video again, since the screenshot carrousel is scrolling. It should instead let you play the video again (that's how it works on Steam).
- [ ] If you let the screenshot carrousel play and it scrolls to a video, the video won't play in its entirety. Instead, the screenshot carrousel will keep scrolling.
- [ ] If you scroll from a video to a screenshot, the automatic scrolling from the screenshot carrousel won't work.
