### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#93]
In each game info tab, there'd be 5 stars above the banner which you can click. That way, you can rate each game based on how much you like it. Then, a "Search by ranking" tab would show you the five different rankings (5 - 1 stars), alongside "Unranked".
![RankingSystem](https://github.com/AlexisL61/JackboxUtility/assets/93792993/18c6b0e2-dac1-41c2-bbbd-433079a3b690)
![RankingMockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/31779032-5e92-4caf-8806-5bfc81955ba1)
And yes, instead of the "Favorites" tab, there'd be this, which I think is much cooler.

**Comment by DerErizzle** [comment]
Really like the idea, however, it doesn't feel natural to filter by 5-star games, 4-star games, and so on. It'd make more sense to show every game, just sorted by how many stars you gave it (just like in #97 suggested). The stars should be hidden in the launcher when it's unranked. Also, I do have the results to the official JBG user survey they did a couple of months ago. Maybe we want to have the option to set all of the ratings to the public votes. A lot of people don't know which game they should play and having these suggestions based on popularity could really help. Just writing down my thoughts on this. Maybe we can have have the stars ranked in a slightly desaturated color by default, which shows the community votes, and when you click on it, it gets replaced with your own ranking (1-5 stars) (https://i.imgur.com/VSuJVpT.png). And when you click on the same amount of stars you gave the game again, it should remove your ranking.
