### ISSUE TITLE
Optional sound effects for the Launcher

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#98]
The launcher should have the option to play sound effects when hovering over the banners, clicking them, going back from the info tab and opening a game. These should be enabled or disabled by default depending on the server. Below is a mockup of how I think should play:
https://github.com/AlexisL61/JackboxUtility/assets/93792993/5d34e56d-3dab-44e0-ad24-ed1aa04b83fc
Now, about how to toggle the enabling/disabling of them, I'd really like it to be in the Launcher part itself and NOT in the Settings part. Not only because this setting is for the Launcher **only**, but also because it really wouldn't take much space if it's one of the buttons at the bottom like the hide unowned games button. Also because the Settings...doesn't really have like a "Toggles" tab, so it'd look really out of place and unnoticed.
![SFXOptionMockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/23b9e8b4-84e2-4839-86fa-455be34c0d6f)

**Comment by DerErizzle** [comment]
As discussed earlier, sfx are a big no-no. I've asked others about their opinion on this and all of them agreed. This app should not become more of a game by adding sfx. Also, like Alexis mentioned earlier, having a setting not in... the settings, is super unintuitive. I get that it's only for the launcher, but it has nothing to do with filtering and searching for games, which is the purpose of the section on the left. Also adding that if you want to include this, you don't want to toggle it off and on anytime, so I don't see a problem with this being "more hidden" in the settings. For the German server, we definitely don't want this feature

**Comment by AkiraArtuhaxis** [comment]
> As discussed earlier, sfx are a big no-no. I've asked others about their opinion on this and all of them agreed. This app should not become more of a game by adding sfx. Also, like Alexis mentioned earlier, having a setting not in... the settings, is super unintuitive. I get that it's only for the launcher, but it has nothing to do with filtering and searching for games, which is the purpose of the section on the left. Also adding that if you want to include this, you don't want to toggle it off and on anytime, so I don't see a problem with this being "more hidden" in the settings. For the German server, we definitely don't want this feature

This definitely varies by community, as in my server not a single person said "No" to the sound effects. If the option doesn't look out of place, it can be in the Settings. And it can stay in the Settings on every server. Only the option to leave it on or off by default would vary depending on the server. So it a German user wants to enable them, they can. The option doesn't need to be hidden entirely depending on the server.
