### ISSUE TITLE
Hiding the games you don't want to see in the launcher

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#99]
This being because they're prequels (you don't care about Quiplash 1, 2 or 3 from PP7 if you have Quiplash 3 from the Starter) or you just... don't like them (Zeeple Dome xd). It'd be a button right next to the Play button on each info tab, and before hiding it there'd be a confirmation to do it. One of the toggles would be to see the hidden games.
![HiddenGamesButton](https://github.com/AlexisL61/JackboxUtility/assets/93792993/f6fe1e89-d037-4dd6-8d76-f4d3f20a7600)
![SFXOptionMockup](https://github.com/AlexisL61/JackboxUtility/assets/93792993/4c32bdf3-dda2-4cb5-954f-f9e9d927b340)
These hidden games wouldn't appear anywhere (including in the "Random game" tab), except in the "Search by game" section. They should always appear there.

**Comment by DerErizzle** [comment]
I think this is not necessary with a ranking system. If you don't like a game, just give it one star and sort by rating. We need to be careful that we don't clutter up the side with filters, toggles and buttons *too much*, and this option is just unnecessary imo

**Comment by AkiraArtuhaxis** [comment]
> 

Definitely not unnecessary. Both the Steam and GOG launchers have the option to hide the games you want. This is because if you buy bundles that include games you don't want, you can hide them (since you're absolutely never gonna play/install them). Same case here with the Jackbox games. Because these come in Packs, these include games you don't like or are outdated (prequels).
If you give them the one star rating, you still see them in All games, the tags and they appear in the Random option. That's not a solution, that's just a workaround.
